### ISSUE TITLE
Write a tab component

### ISSUE THREAD

**Issue by cburgdorf** [thoughtram-editor/editor#1]
We probably want to have tabs to create files (similar to sublime, atom and probably any other editor).

This would make a great Angular2 component example, too

**Comment by 0x-r4bbit** [comment]
I agree with the second statement. However, when it comes to UI I'd like to have something simpler and cleaner. More like http://requirebin.com

**Comment by 0x-r4bbit** [comment]
Closing this for now. Tabs are (at least rudimentary) implemented at http://github.com/thoughtram/angular-tabs
